# Generated by Selenium IDE
#import pytest
import time
import json

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from config import *
import os

try:
    os.remove("downloads/Export_dashboard.csv")
    os.remove("downloads/Export_dashboard(1).csv")
    os.remove("downloads/Export_dashboard(2).csv")
except FileNotFoundError:
    print("One of the files was not found")

# Globals that would need to be configured
executable_path = r'F:\Users\Peter\Documents\Zonatel_scraper\Zonatel_scraper\geckodriver.exe'

fp = webdriver.FirefoxProfile()
fp.set_preference("browser.download.folderList", 2)
fp.set_preference("browser.download.dir", "F:\\Users\\Peter\\Documents\\Zonatel_scraper\\Zonatel_scraper\\downloads")
fp.set_preference("browser.helperApps.neverAsk.openFile", "application/csv, txt/csv")
fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/csv, txt/csv, text/csv, attachment/csv, multipart/form-data")

driver = webdriver.Firefox(firefox_profile=fp, executable_path=executable_path)

# Navigate to and login
driver.get(URL)
driver.set_window_size(1173, 817)
driver.find_element(By.ID, "user_email1").click()
driver.find_element(By.ID, "user_email1").send_keys(USERNAME)
driver.find_element(By.CSS_SELECTOR, "html").click()
driver.find_element(By.ID, "user_password").click()
driver.find_element(By.ID, "user_password").send_keys(PASSWORD)
driver.find_element(By.ID, "user_password").submit()
driver.execute_script("window.scrollTo(0,0)")

# Nav to dashboard
time.sleep(5)
driver.find_element(By.ID, "dashboard-button").click()
time.sleep(6)

# Config date range to be today + tmr
end_date = driver.find_element_by_xpath("//*[contains(@ng-click, 'openedEndDate ')]")
end_date_val = end_date.get_attribute('value')
print(end_date_val)

start_date = driver.find_element_by_xpath("//*[contains(@ng-click, 'openedStartDate ')]")
print(start_date.get_attribute('value'))
start_date.clear()
end_date.clear()
start_date.send_keys(end_date_val)
end_date.send_keys(end_date_val + str(1))
# end_date.("value", end_date_val+1)





driver.find_element_by_xpath("//*[contains(text(), '+filters')]").click()
time.sleep(5)

# Select filters
# driver.find_element_by_xpath("//*[contains(text(), 'Follow Up Calls_f')]").click()
# follow_up_calls = driver.find_elements_by_xpath("//*[contains(text(), 'Follow Up Calls_f')]")[1]
follow_up_calls = driver.find_elements_by_xpath("//*[contains(@ng-click, 'onClickQueueFilter')]")[5]
# print(f"button: {follow_up_calls}")
follow_up_calls.click()


# Apply Filter
apply_filters = driver.find_element_by_xpath("//*[contains(@ng-click, 'applyFilterBox()')]")
apply_filters.click()

time.sleep(5)

# Download
download = driver.find_element_by_xpath("//*[contains(@ng-click, 'activateOnDownloadCsv')]")
download.click()

# clear filters, repeat
driver.find_elements_by_xpath("//*[contains(text(), 'clear')]")[21].click()

driver.find_element_by_xpath("//*[contains(text(), '+filters')]").click()

# TODO get follow up calls too




# time.sleep(3)
# dmg_assessment = driver.find_elements_by_xpath("//*[contains(@ng-click, 'onClickQueueFilter')]")[2] # 2, 4, 6
# intake_eligibility = driver.find_elements_by_xpath("//*[contains(@ng-click, 'onClickQueueFilter')]")[4]
# status_checks = driver.find_elements_by_xpath("//*[contains(@ng-click, 'onClickQueueFilter')]")[6]
#
# dmg_assessment.click()
# intake_eligibility.click()
# status_checks.click()
#
# time.sleep(5)



# ActionChains(driver).move_to_element(follow_up_calls).click()
# print("clicked")
# ActionChains(driver).move_to_element(follow_up_calls).perform()
# action.click()
# action.perform()


# web debugging: $x("//*[contains(text(), 'Follow Up Calls_f')]")

# driver.find_element_by_xpath("//*[contains(text(), 'Follow Up Calls')]").click()
# driver.find_element_by_xpath("//*[contains(text(), 'Intake/Eligibility')]").click()
# driver.find_element_by_xpath("//*[contains(text(), 'Status Checks')]").click()
